openapi: 3.0.3
info:
  title: Simple API Example
  description: Пример простого API для управления задачами
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /tasks:
    get:
      summary: Получить список задач
      description: Возвращает список всех задач
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Создать новую задачу
      description: Добавляет новую задачу в список
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Задача успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{taskId}:
    get:
      summary: Получить задачу по ID
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID задачи
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задача не найдена
    put:
      summary: Обновить задачу
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID задачи
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Задача обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Удалить задачу
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID задачи
          schema:
            type: integer
      responses:
        '204':
          description: Задача удалена
        '404':
          description: Задача не найдена

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор задачи
        title:
          type: string
          description: Название задачи
        description:
          type: string
          description: Описание задачи
        completed:
          type: boolean
          description: Статус выполнения
      required:
        - id
        - title
        - completed
    TaskInput:
      type: object
      properties:
        title:
          type: string
          description: Название задачи
        description:
          type: string
          description: Описание задачи
        completed:
          type: boolean
          description: Статус выполнения
      required:
        - title
        - completed